### ISSUE TITLE
v61.2 has a wrong drop_table definition

### ISSUE THREAD

**Issue by stackmystack** [JesseChavez/activerecord-jdbc-adapter#16]
This definition of the opts hash https://github.com/JesseChavez/activerecord-jdbc-adapter/blob/v61.2.0/lib/arjdbc/mssql/schema_statements.rb#L141 is dead wrong. It needs to be a `**opts` [just like what you have on `master`](https://github.com/JesseChavez/activerecord-jdbc-adapter/blob/stable-dev/lib/arjdbc/mssql/schema_statements.rb#L150).

The moment you call super https://github.com/JesseChavez/activerecord-jdbc-adapter/blob/v61.2.0/lib/arjdbc/mssql/schema_statements.rb#L160 it explodes.

Is there any chance you'd release a newer v61 soon? (I can see that 61.3 is dead wrong especially that it doesn't have arjdbc/mssql).

I can write the patch (because I might discover other issues that need to be fixed), I just want to know what's the pulse on the project.

**Comment by stackmystack** [comment]
v60 is also affected.

**Comment by JesseChavez** [comment]
Hi @stackmystack 

it would be good if you provide a patch, I can release a patch version.

I didn't have the chance to test in several versions of sql server

**Comment by JesseChavez** [comment]
Hi @stackmystack 

I fixed the issue and release an new version

[61.3.0](https://rubygems.org/gems/activerecord-jdbc-alt-adapter/versions/61.3.0-java)

I'm closing this issue

**Comment by stackmystack** [comment]
Thanks @JesseChavez !
